naftiko: 1.0.0-alpha2
info:
  label: Acquia Cloud API Documentation — Email
  description: 'Acquia Cloud API Documentation — Email. 1 operations. Lead operation: Returns the status of Platform Email
    for an Environment.. Self-contained Naftiko capability covering one Acquia business surface.'
  tags:
  - Acquia
  - Email
  created: '2026-05-19'
  modified: '2026-05-19'
binds:
- namespace: env
  keys:
    ACQUIA_API_KEY: ACQUIA_API_KEY
capability:
  consumes:
  - type: http
    namespace: cloud-openapi-full-email
    baseUri: ''
    description: Acquia Cloud API Documentation — Email business capability. Self-contained, no shared references.
    resources:
    - name: environments-environmentId-email
      path: /environments/{environmentId}/email
      operations:
      - name: getemailstatus
        method: GET
        description: Returns the status of Platform Email for an Environment.
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
    authentication:
      type: bearer
      token: '{{env.ACQUIA_API_KEY}}'
  exposes:
  - type: rest
    namespace: cloud-openapi-full-email-rest
    port: 8080
    description: REST adapter for Acquia Cloud API Documentation — Email. One Spectral-compliant resource per consumed operation,
      prefixed with /v1.
    resources:
    - path: /v1/environments/{environmentid}/email
      name: environments-environmentid-email
      description: REST surface for environments-environmentId-email.
      operations:
      - method: GET
        name: getemailstatus
        description: Returns the status of Platform Email for an Environment.
        call: cloud-openapi-full-email.getemailstatus
        outputParameters:
        - type: object
          mapping: $.
  - type: mcp
    namespace: cloud-openapi-full-email-mcp
    port: 9090
    transport: http
    description: MCP adapter for Acquia Cloud API Documentation — Email. One tool per consumed operation, routed inline through
      this capability's consumes block.
    tools:
    - name: returns-status-platform-email-environment
      description: Returns the status of Platform Email for an Environment.
      hints:
        readOnly: true
        destructive: false
        idempotent: true
      call: cloud-openapi-full-email.getemailstatus
      outputParameters:
      - type: object
        mapping: $.
